### ISSUE TITLE
Moondeck crashing gamemode

### ISSUE THREAD

**Issue by xfechx** [FrogTheFrog/moondeck-buddy#77]
Hello,

Suddenly - when attempting to run moondeck, by clicking a game moondeck icon (when connected to HDMI) it doesn't do anything, but it crashes game mode, and I cannot bring the steam menu or the right menu at all. I then have to do a force-reset in order to have it work again.

I have restored OS, uninstalled and installed moondeck, and decky, without any luck. 

How can I completely uninstall moondeck and all it's options?

This does not happen if I run moondeck in handheld (non docked) mode.

Thanks

**Comment by FrogTheFrog** [comment]
Hello,
that's strange, I use it docked myself and it does not happen :/

> How can I completely uninstall moondeck and all it's options?
To completely remove it, install it again (buddy is not needed), go to MoonDeck settings and there will be "Shortcuts" and "Sunshine Apps" tabs. Simply click on the buttons to purge shortcuts.

Then uninstall MoonDeck and remove `~/.config/moondeck` directory from SteamDeck.

**Comment by xfechx** [comment]
Hi, 

I have done that already. I have two steam decks, and in one it does not happen.

What else can I do to wipe moondeck? 
How can I look at the error?

**Comment by FrogTheFrog** [comment]
> What else can I do to wipe moondeck?
Nothing, that's all the info that MoonDeck stores outside of Decky

> How can I look at the error?
You could try debugging it via chromium, maybe some obvious errors are logged or check `journalctl`. To do that you'll need to join Decky's discord and ask around.

**Comment by xfechx** [comment]
Ok, so it was fixed after me messing around with the settings, but again it
broke by itself suddenly.

I didn't make any changes to the settings. Now I have to mess up with
settings to see what fixes it again.

**Comment by FrogTheFrog** [comment]
Did you get it fixed in the end?

**Comment by xfechx** [comment]
Sometimes still happens, and it crashes my whole thing. When it happens, I
have to force shutdown (like with ssh) or force reboot. Not sure what is
the issue, but yes - still happens from time to time.

**Comment by xfechx** [comment]
It happens constantly actually. I dont know how to fix it. And I have to
hard reboot.

I am afraid of using it now, been using steam remote, although I prefer
moonlight.

**Comment by FrogTheFrog** [comment]
Have you tried debugging it via chromium?
See here on how to set it up:
https://docs.deckthemes.com/CSSLoader/Cef_Debugger/#recommended-setup
